apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 5000
      targetPort: 5000
      name: http
  selector:
    app: phpmyadmin