apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: image_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000