apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 5050
      nodePort: 5050
      targetPort: 5050
      name: http
  selector:
    app: wordpress