apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: image_ftps
        imagePullPolicy: Never
        # livenessProbe:
        #   exec:
        #     command:
        #     - sh
        #     - healthy.sh
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        ports:
        - containerPort: 21
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      name: http
  externalIPs:
    - 192.168.99.242
  selector:
    app: ftps