apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: image_phpmyadmin
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - healthy.sh
          initialDelaySeconds: 30
          periodSeconds: 60
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  externalIPs:
    - 192.168.99.242
  selector:
    app: phpmyadmin