apiVersion: apps/v1 
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: image_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
      # nodePort: 5000
      targetPort: 5000
      name: http
  selector:
    app: phpmyadmin