apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: image_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050